### ISSUE TITLE
Matrix.to_euler - Argument missing for parameter "euler_compat"

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#236]
```python
from mathutils import Matrix

# Argument missing for parameter "euler_compat"
print(Matrix().to_euler("XYZ"))
```

typing error though `euler_compat` is optional:
![image](https://github.com/nutti/fake-bpy-module/assets/9417531/417ce361-67ff-47b0-9805-525ae072c6d0)

**Comment by nutti** [comment]
This issue is now fixed.

**Comment by Andrej730** [comment]
@nutti it's still an issue for fake-bpy-module-latest==20240719

**Comment by nutti** [comment]
@Andrej730 
What is the issue?
I could not find the image.

**Comment by Andrej730** [comment]
@nutti oh, sorry, the issue is the same - it's requesting the argument that is optional.

![image](https://github.com/user-attachments/assets/3783ffa6-4402-4f46-9886-410feab1f3d7)

**Comment by nutti** [comment]
Fixed now.
