### ISSUE TITLE
Typing issue assigning Vector to a slice of Vector

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#336]
See example below.

```python
from mathutils import Vector

v = Vector()
v.xyz = (1, 2, 3)
print(v)  # Vector((1.0, 2.0, 3.0))
# Typing Error: No overloads for "__setitem__" match the provided arguments
v[:] = Vector()
print(v)  # Vector((0.0, 0.0, 0.0))
```

**Comment by nutti** [comment]
Fixed this issue now.

**Comment by Andrej730** [comment]
@nutti 
The issue is still present for `Vector` - https://github.com/nutti/fake-bpy-module/blob/1a2acda0d8664906a49e6255ab8824d0c9ef387f/src/mods/common/analyzer/append/mathutils.mod.rst?plain=1#L380

For color it probaly should be able to accept `Color` instead of `Vector`. Also noticed similar issue for othe classes, full example:
```python
from mathutils import Vector, Color, Quaternion, Euler, Matrix

v = Vector()
v.xyz = (1, 2, 3)
print(v)  # Vector((1.0, 2.0, 3.0))
# Typing Error: No overloads for "__setitem__" match the provided arguments
v[:] = Vector()
v.__setitem__
print(v)  # Vector((0.0, 0.0, 0.0))

c = Color()
# No overloads for "__setitem__" match the provided arguments
c[:] = c
c.__setitem__
print(c)

q = Quaternion()
# No overloads for "__setitem__" match the provided arguments
q[:] = q
q.__setitem__

e = Euler()
# No overloads for "__setitem__" match the provided arguments
e[:] = e
e.__setitem__

m = Matrix()
# No overloads for "__setitem__" match the provided arguments
m[:] = m * 10
m[0] = Vector((1,0,0,0)) # Works fine.
print(m)
```
